### ISSUE TITLE
yeti should barf in a friendly way when it encounters syntax errors

### ISSUE THREAD

**Issue by majensen** [CBIIT/yeti#3]
Can yeti help find syntax errors?

**Comment by PhilipMusk** [comment]
Example: in the case of simple indent errors, opening the yaml file via Yeti results in the first error being corrected, but lines already correctly indented but appearing downstream of said indent error are "lost", because they're "out of frame" with the errant line. As expected, 3 incorrectly indented properties one after the other, each "off" by the same degree all get corrected. But anything in the way of properties already correctly indented, but downstream of the 3 incorrectly indented lines, gets converted into a string, with "-" separating what were properties. Having Yeti fully correct syntax errors seems a little over ambitious, so a better solution might be to have the tool throw a warning that the yaml file to be viewed/edited has got syntax errors that should be fixed?
